### ISSUE TITLE
getDevices returns an empty array

### ISSUE THREAD

**Issue by hertzg** [andrewrk/node-groove#13]
Calling getDevices returns an empty array
```
var groove = require('groove'), devs = groove.getDevices()
console.log('devices=%j length=%j', devs, devs.length)
```
returns
```
$ node main.js 
devices=[] length=0
```

although not specifying `deviceIndex` in `GroovePlayer`, Plays audio on default pulseaudio sink.

I believe this is a bug and getDevices() should at least return the default device name.

**Comment by andrewrk** [comment]
I looked into this, and got the same behavior as you. SDL_GetNumAudioDevices is returning -1 which means "an explicit list of devices can't be determined". This is not good behavior so libgroove may look into switching from SDL2 to PortAudio.

See https://github.com/andrewrk/libgroove/issues/84

**Comment by hertzg** [comment]
The SDL wiki for [SDL_GetNumAudioDevices](http://wiki.libsdl.org/SDL_GetNumAudioDevices) has following remark:

```
In many common cases, when this function returns a value <= 0, it can still successfully open the default device (NULL for first argument of SDL_OpenAudioDevice()).

This function may trigger a complete redetect of available hardware
```

So I tried calling the function after `groove.createPlayer()` and got the following output:
```
$ node main.js
devices=[] length=0
devices=["System audio output device"] length=1
```
I think manually triggering "a complete redetect of available hardware"  before calling `getDevices()` would solve the problem

**Comment by andrewrk** [comment]
`getDevices()` does in fact call `SDL_GetNumAudioDevices` already.

**Comment by hertzg** [comment]
I think call to [`SDL_InitSubSystem(SDL_INIT_AUDIO)`](http://wiki.libsdl.org/SDL_InitSubSystem) in [`groove_player_create`](https://github.com/andrewrk/libgroove/blob/master/grooveplayer/player.c#L295) did some initialization required for [`SDL_GetNumAudioDevices`](http://wiki.libsdl.org/SDL_GetNumAudioDevices)

**Comment by andrewrk** [comment]
Ah yes good point.

```js
var groove = require('groove');
var player = groove.createPlayer();
console.log(groove.getDevices());
```

With this code, I get `[ 'System audio output device' ]`.

Looks like there should be more devices though:

![](http://i.imgur.com/7taM5cU.png)

I haven't checked yet what PortAudio would say for the list of devices.

**Comment by hertzg** [comment]
Indeed there should be more

![screenshot from 2015-01-21 03 17 17](https://cloud.githubusercontent.com/assets/1886698/5828313/17f299b8-a11c-11e4-9fac-26cf30508eb0.png)

**Comment by hertzg** [comment]
I can think of these two solutions to this issue for now
* Providing some "init" and "deinit" kind of methods to JS userspace
* Calling `SDL_InitSubSystem` before `SDL_GetNumAudioDevices` and keeping track of Subsystem initializations states

Or just monkey patching to something like this before moving to PortAudio
```
int groove_device_count(void) {
    SDL_InitSubSystem(SDL_INIT_AUDIO);
    int count = SDL_GetNumAudioDevices(0);
    SDL_QuitSubSystem(SDL_INIT_AUDIO);
    return count;
}
```

**Comment by andrewrk** [comment]
Your suggestion, which I think is a good idea, would cause `groove_device_count` to return 1 instead of -1 (and hence `getDevices()` to return `[ 'System audio output device' ]` instead of `[]`. But is this a satisfactory situation? It is my understanding that you want to actually list your devices, is that correct?

I did a test with PortAudio:

```c
#include <portaudio.h>
#include <stdio.h>

int main() {
    PaError err = Pa_Initialize();

    if (err != paNoError) {
        fprintf(stderr, "unable to init PortAudio: %s\n", Pa_GetErrorText(err));
        return -1;
    }

    int device_count = Pa_GetDeviceCount();
    for (int i = 0; i < device_count; i += 1) {
        const PaDeviceInfo *device_info = Pa_GetDeviceInfo(i);
        printf("device: %s\n", device_info->name);
    }

    err = Pa_Terminate();
    if (err != paNoError) {
        fprintf(stderr, "unable to terminate PortAudio: %s\n", Pa_GetErrorText(err));
        return -1;
    }
    return 0;
}
```

On my machine, outputs:

```
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm_route.c:947:(find_matching_chmap) Found no matching channel map
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
bt_audio_service_open: connect() failed: Connection refused (111)
ALSA lib pcm_dmix.c:1022:(snd_pcm_dmix_open) unable to open slave
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
device: HDA Intel PCH: ALC892 Analog (hw:0,0)
device: HDA Intel PCH: ALC892 Digital (hw:0,1)
device: HDA Intel PCH: ALC892 Alt Analog (hw:0,2)
device: HDA NVidia: HDMI 0 (hw:1,3)
device: HDA NVidia: HDMI 1 (hw:1,7)
device: sysdefault
device: iec958
device: spdif
device: pulse
device: default
device: /dev/dsp
```

**Comment by hertzg** [comment]
There are two reasons why I need to call `getDevices()`
1. Get the list of names of available devices
2. Choose appropriate output device for `GroovePlayer` via `deviceIndex`

Currently calling `getDevices()` returns an empty array which is obviously an incorrect behavior.
I also agree that not listing all the available devices is not a desired behavior. But I believe the problem is woth SDL itself not being able to detecting output devices.

My solution was a mere fix of current issue where `getDevices()` returns an empty array but can still play audio and after calling createPlayer() returns different result. Which I think is a bug.

The real solution depends on the projects plan. I would love to help but I don't have much experience with C/C++.

**Comment by andrewrk** [comment]
Here's another workaround: call createPlayer() before calling getDevices(). I don't see why it matters though, since the device list is not returning anything useful. You can just assume there is 1 device, the default player. You'll have to wait until libgroove improves its ability to get a device list before the getDevices() API is useful.

**Comment by andrewrk** [comment]
This is fixed in master branch, but you'll want to wait until the next release because I'm synchronizing it with the release of libsoundio and a major version release of libgroove.
