### ISSUE TITLE
Node abort on insert 

### ISSUE THREAD

**Issue by jm21** [andrewrk/node-groove#14]
I've installed node-groove on a raspberry pi based on the instructions on your site. Am trying to play a song  which is coming from a signed url e.g. https://d2mxawcko1ots5.cloudfront.net/normalized/g770gbe0-07.mp3?Expires=1429215344&Signature=mBA3Yd~IPaFwBKegUl0XVd7qXc5-x7y43sQp82YaOaT8dVnIQ2O0Jlfj5QhP3CjFIXUBx~mUWgG1nPDtbci188j2Pox7TXN3-FWR7B~HKSxiPW-a5HWqqd8XfS08xOIGzgTGtqPMY1mAE0KmRKVTPuOG5t3B2t29d5o-7qw3zemj0Ay3SDZL5pPNOxD1wHTri~~iwK1~8eJCRd38zm4tz36HEZ36mHFAzgozB8OE-91wKvAGpk~UWNwtlUcGdUHBuKudeJr7r4itLVB7XVVfrM-dYTDsWY0aA0LRUQ4XhiWxvbYIE~TEU5MgmdKl3AtIrgnDyLxvx5cOav~UtXlJIg__&Key-Pair-Id=APKAJSOAJCVZOBE4CSRQ

Am using the code below to try and play the song

var song = data.songurl   ; 
      var playlist = groove.createPlaylist()
      var player = groove.createPlayer()
      playlist.insert(song)
      player.attach(playlist, function(err){
        console.log(err)
      })

Am getting the following error on playlist.insert(song):

node: /home/pi/.node-gyp/0.11.16/src/node_object_wrap.h:50: static T*
node::ObjectWrap::Unwrap(v8::Handle<v8::Object>) [with T = GNFile]:
Assertion `handle->InternalFieldCount() > 0' failed.
Aborted

Any idea what could be wrong?

**Comment by andrewrk** [comment]
`playlist.insert` expects a `GrooveFile` object, not a `String`. Check out the example folder for proper usage.

**Comment by jm21** [comment]
Sorry for bothering you like this, am not a javascript guru so am a bit lost. In your examples you process.argv as the object. Am getting a variable which contains the url for the mp3, how would I change this to a groove object? I've tried 
var song = []; 
song.push(data.songurl)

Still getting the same error on playlist insert

**Comment by andrewrk** [comment]
Try looking at the playlist example.

Stream playback is not currently supported; only opening files from a local file system.

**Comment by jm21** [comment]
Ah, than the solution won't work for me. Am getting the mp3s from a music service as signed url's and I can't download them. Thanks for your help

**Comment by andrewrk** [comment]
If you can't download them then you can't stream them either. Streaming is the same thing is downloading.
