### ISSUE TITLE
install fails: build error

### ISSUE THREAD

**Issue by geoguide** [andrewrk/node-groove#15]
I'm relatively new to npm so I'm not sure how to debug this sort of error:

../src/file.h:6:10: fatal error: 'groove/groove.h' file not found
#include <groove/groove.h>
         ^
1 error generated.
make: *** [Release/obj.target/groove/src/groove.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 14.3.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/geoffguidetti/Documents/Git/audio-experiment/node_modules/groove
gyp ERR! node -v v0.12.2
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "--save" "groove"
npm ERR! node v0.12.2
npm ERR! npm  v2.7.5
npm ERR! code ELIFECYCLE

npm ERR! groove@2.3.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groove@2.3.3 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the groove package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls groove
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/geoffguidetti/Documents/Git/audio-experiment/npm-debug.log

**Comment by andrewrk** [comment]
Typically when you see that ______.h file not found (in this case groove.h) then you are missing the associated library. Take a peek at the [libgroove installation instructions](https://github.com/andrewrk/libgroove) (if you have debian or ubuntu then it's already in apt-get).

**Comment by geoguide** [comment]
Oh, I completely missed that! Thank you. Isn't npm supposed to take care of dependencies? That is confusing to me, I thought that was the point of it, shouldn't it grab those first?

**Comment by andrewrk** [comment]
Normally, yes. However in this situation libgroove depends on libav/ffmpeg, which is a library so huge that it makes more sense to install it globally on your system and link against that than to bundle it in an npm package.

So what ends up happening is that libgroove is bundled up in a way that depends on libav/ffmpeg (as well as some other C libraries), so you end up relying on your system's packaged up version of those libraries which contains patches and fixes that are relevant to your system. This is a little inconvenient in terms of getting all dependencies from npm, but it ends up being more convenient in the long run, avoiding a bunch of subtle problematic conditions.

**Comment by geoguide** [comment]
Thanks! That helps a lot.

**Comment by andrewrk** [comment]
Oh, and I noticed you're on OSX, so you can install libgroove via homebrew and that will pull in all the dependencies you need.

**Comment by geoguide** [comment]
Sweet! Thanks.
