### ISSUE TITLE
Crashes when file.close()

### ISSUE THREAD

**Issue by moonwave99** [andrewrk/node-groove#19]
I am running node-groove in a [Atom Electron](https://github.com/atom/electron) environment.

With the following scenario:

- load some files into a `GroovePlaylist`;
- get a reference to playlist items before cleaning;
- clear playlist;
- run `.close()` on the items.

App freezes, without throwing any error [even if playlist was not playing at all].

Simplified code follows:

    var playlist = groove.createPlaylist()

    Promise.all(album.tracks.map((track)=>{
      return new Promise((resolve, reject)=>{
        groove.open(track.filename, (err, file)=>{
          if(err){
            reject(err)
          }else{
            resolve(file)
          }
        })
      })
    })).then((files)=>{
      // this is an array of Groove files
      files.forEach( file => playlist.insert(file) )
  
      var itemsToClear = playlist.items()
      playlist.clear()
  
      Promise.all(itemsToClear.map((item)=>{
        return new Promise((resolve, reject)=>{
          item.file.close((err)=>{ // #OUCH
            // notice that I do not even manage to get in here, so no js Error
            if(err){ reject(err) 
            }else{ resolve(item) }
          })
        })
      })).then((clearedItems)=>{
        // here I would expect to find a list of the cleared items
      })
    })

---

The idea is to load a single album at time into Groove, then to clear the playlist every time I switch to a different album, in order not to have too many files open.

Which is the correct way to call `.close()` then?

Thank you for your time.

**Comment by andrewrk** [comment]
A PlaylistItem is only meant to exist as a pointer into the playlist. So if you clear the playlist, the playlist items don't exist any more and any playlist item objects you have lying around are dangling pointers waiting to cause ruckus in your code.

[examples/playlist.js](https://github.com/andrewrk/node-groove/blob/master/example/playlist.js#L50) demonstrates getting all the files out of a playlist before clearing it. Try that.

I don't blame you for making this mistake; your code looked fine until I examined the C API and realized the problem. I'll look into making this kind of mistake harder to make in future versions of node-groove.

**Comment by moonwave99** [comment]
Hey Andrew, thank you for the very prompt response.

Everything is clear now - though I originally went through your `playlist.js` example for implementing the playlist behaviour, I overlooked that I needed to gather all the `GrooveFile`s before clearing, and not just the `GroovePlaylistItem`s.

Works like a charm now!

**Comment by andrewrk** [comment]
Great! I'll leave this issue open until I resolve the API problem of how easy it is to do this on accident.
