### ISSUE TITLE
io.js 3 support

### ISSUE THREAD

**Issue by pierreinglebert** [andrewrk/node-groove#21]
In order to support io.js 3 and the upcoming new stable nodejs, nan dependency should be upgraded to 2.

**Comment by andrewrk** [comment]
Progress underway in master branch. Ran into a snag: https://github.com/nodejs/nan/issues/440

**Comment by andrewrk** [comment]
OK this is fixed in master branch, but you'll want to wait until I release because I'm synchronizing the release of node-groove 3.0.0, libgroove 5.0.0, and libsoundio 1.0.0.
