### ISSUE TITLE
could not install

### ISSUE THREAD

**Issue by fredele** [andrewrk/node-groove#24]
Hello, I' m trying to install groove-node, here's what I got.

`frederic@postefred:~$ npm install --save groove
|
> groove@2.5.0 install /home/frederic/node_modules/groove
> node-gyp rebuild
Usage: gyp_main.py [options ...] [build_file ...]
gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1075:12)
gyp ERR! System Linux 3.19.0-41-generic
gyp ERR! command "node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/frederic/node_modules/groove
gyp ERR! node -v v0.12.9
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok 
npm ERR! Linux 3.19.0-41-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "--save" "groove"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code ELIFECYCLE
npm ERR! groove@2.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the groove@2.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the groove package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls groove
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/frederic/npm-debug.log
frederic@postefred:~$`

I have installed the 3 libs. with sudo apt-get install .....
They show up in synaptic
I'm running ubuntu 15
Any idea ?

**Comment by andrewrk** [comment]
> gyp_main.py: error: no such option: --no-parallel

I'm not sure what would cause this. Something to do with the nodejs or gyp or node-gyp installation being out of sync.

**Comment by fredele** [comment]
Yes, it' on Ubuntu.
I'll try to fix it by reinstalling everything.

Thanks for your reply
Merry christmas
