### ISSUE TITLE
Can't inspect node-groove playlist object with console.dir

### ISSUE THREAD

**Issue by whmountains** [andrewrk/node-groove#8]
As the title says, when I try to dump the node-groove playlist object with `console.dir(playlist)`, I get an output of simply `{}`.  This is right after I've created the playlist:

```
var playlist = groove.createPlaylist();
console.dir(playlist);
````
This is frustrating because that means it's hard to debug code that operates on these objects.  For example,

```
console.dir(playlist.items());
//in my case returns [{},{}]
var files = _.pick(playlist.items(), 'file');
console.dir(files);
//returns {}
````
I can't figure out why `_.pick` isn't working if I can't even see the variable.  (I suspect it can't see it either.)

This is probably some obvious newbie issue, (I haven't been coding in javascript for very long.) or it might actually be a bug.  At any rate, I'd appreciate some enlightenment.

EDIT: I have this same problem if I put `console.dir(playlist);` right after the playlist declaration in the `examples/playlist.js` example file.  It still returns `{}` but then goes on to play the audio file I asked it to.

P.S. I love node-groove <3

**Comment by andrewrk** [comment]
Sorry, I think the best resolution to this is going to be to have detailed documentation in the README.
